"""empty message

Revision ID: 1492c50ab1d2
Revises: None
Create Date: 2016-04-18 15:18:44.227349

"""

# revision identifiers, used by Alembic.
revision = '1492c50ab1d2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('timestamp_creation', sa.DateTime(), nullable=False))
    op.add_column('article', sa.Column('timestamp_publish', sa.DateTime(), nullable=False))
    op.add_column('news', sa.Column('timestamp_creation', sa.DateTime(), nullable=False))
    op.add_column('news', sa.Column('timestamp_publish', sa.DateTime(), nullable=False))
    op.add_column('video', sa.Column('timestamp_creation', sa.DateTime(), nullable=False))
    op.add_column('video', sa.Column('timestamp_publish', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'timestamp_publish')
    op.drop_column('video', 'timestamp_creation')
    op.drop_column('news', 'timestamp_publish')
    op.drop_column('news', 'timestamp_creation')
    op.drop_column('article', 'timestamp_publish')
    op.drop_column('article', 'timestamp_creation')
    ### end Alembic commands ###
